name = "assignment2"
description = ""
version = "0.1.0-dev"

authors = ["Ingmar Falk"]
maintainers = ["Ingmar Falk <example@example.com>"]
maintainers-logins = ["github-username"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []
